### ISSUE TITLE
Integrate process_mappings function to be within process_mappings?

### ISSUE THREAD

**Issue by danielecook** [AndersenLab/cegwas#10]
How do you feel about integrating the `process_pheno` function to be within the `gwas_mappings` function? And...maybe to also integrate `process_mappings` within `gwas_mappings` as well?

If these steps are _always_ performed as a part of mappings wouldn't they be better off within the gwas_mappings function? You can make them internal functions and not export them to make them less visible...

What do you think?

**Comment by synmuv** [comment]
I think it sounds like a good idea. If we don't need the intermediate data, then why output it?

**Comment by Thatguy027** [comment]
to see where things break if they do. this was an issue a year ago that Ty-Ty spent this summer fixing. before he came this summer we all agreed to break up any pipeline into manageable units that can be fixed by other people and not some annoying pipeline only Ty-Ty can fix. 

with that in mind i decided to break the pipeline up by specific tasks.... process phenotypes, map, process mappings, plot

**Comment by danielecook** [comment]
I added the `map` function to address this. May want to extend it's functionality as time goes on.
