### ISSUE TITLE
Alternative strain names need to be incorporated

### ISSUE THREAD

**Issue by synmuv** [AndersenLab/cegwas#9]
We use 124 isotypes for GWAS, but we have over 200 strains sequenced. Any of these over 200 strains could be phenotyped. We need to allow for experimenters who have used alternative strains that fall into an isotype set. Also, we need to allow for alternative strain names (e.g. CB4851 instead of CB4851_CGC).

**Comment by Thatguy027** [comment]
need a file that has all possible names for a corresponding genotype

**Comment by synmuv** [comment]
Dan should have it.

**Comment by Thatguy027** [comment]
ooh you got assigned Dan. _walks away_ _brushes dirt off shoulder_

**Comment by danielecook** [comment]
I've given it a go addressing this - there is a file within the `raw-data` folder called `mapping_strain_isotype.tsv` that contains three columns: strain, isotype, and warning. This file is saved into two objects that are used by `process_pheno` which converts strain names to appropriate isotypes and checks whether those strains have any warnings and issues them.

In order to add new warnings or strains, update the `mapping_strain_isotype.tsv` and re-run the `process_data.R` script to regenerate the appropriate data. I have already added the TR403 strain to start. Then commit your changes!

In cases where no isotype is identifiable process_pheno will now throw an error.

Please try this out and let me how it works, any potential problems, or issues you encounter.
